t=input("Escreva algo:")
print('O tipo primitivo é',type(t))
print('Só tem espaço?',t.isspace())
print('É um numero?',t.isnumeric())
print('É alfabetico?',t.isalpha())
print('É alfanumerico?',t.isalnum())
print('Estão em maiúsculas?',t.isupper())
print('Estão em minúsculas?',t.islower())
print('Esta capitalizada?',t.istitle())
